### ISSUE TITLE
In-domain performance

### ISSUE THREAD

**Issue by Joshua1225** [LongLong-Jing/Cross-Modal-Center-Loss#10]
Hi. Could you release checkpoints or features of in-domain retrieval comparsion?
The improvements of that in your jobs are excellent.
Thanks.

**Comment by Joshua1225** [comment]
Could you provide some advice about trainning method in single modal?

**Comment by saladcat** [comment]
> Could you provide some advice about trainning method in single modal?

you mean training? you may implement it by yourself. it's not hard.

**Comment by Joshua1225** [comment]
It is not a problem of implementation.
The in-domain performance reported in the paper on the ModeNet40 dataset is wrong, which is actually the result of the ModelNet10 dataset.  The correct in-domain performance is lower.
